version: '3.9'

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: postgres:16.1
    restart: always
    container_name: postgresql_service
    env_file:
      - .env
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}"
    expose:
      - '${POSTGRES_DOCKER_PORT}'
    networks:
      - app-tier
    
  api:
    # THE build IS USED TO INDICATE THE PATH FROM WHERE THE SERVICE WILL BE BUILT, THE PATH MUST ALWAYS HAVE A Dockerfile
    build: ./api
    restart: always
    container_name: api_service
    ports:
      - "${FAKER_LOCAL_PORT}:${FAKER_DOCKER_PORT}"
    networks:
      - app-tier
    depends_on:
      - db